@FaqService.Api_HostAddress = http://localhost:5064


### get all faqs
GET {{FaqService.Api_HostAddress}}/api/faqs

### get faq by id
GET {{FaqService.Api_HostAddress}}/api/faqs/1

### create faq
POST {{FaqService.Api_HostAddress}}/api/faqs
Content-Type: application/json
{
  "title": "What is the return policy?",
  "summary": "You can return any item within 30 days of purchase for a full refund.",
  "content": "Our return policy allows customers to return items within 30 days of purchase. To initiate a return, please contact our customer service team with your order details. Once we receive the returned item, we will process your refund within 5-7 business days."
}

### update faq
PUT {{FaqService.Api_HostAddress}}/api/faqs/1
Content-Type: application/json
{
  "title": "What is the return policy?",
  "summary": "You can ABSOLUTELY NOT return any item within 30 days of purchase for a full refund.",
  "content": "Our return policy STRICTLY DISallows customers to return items within 30 days of purchase. To initiate a return, please contact our customer service team with your order details. Once we receive the returned item, we will process your refund within 5-7 business days."
}

### delete faq
DELETE {{FaqService.Api_HostAddress}}/api/faqs/1